#!/usr/bin/env bash

erl_dir=/usr/lib/cruxis
cruxis_conf_dir=/etc/cruxis

# erlang gets mad if run with $HOME empty
if [[ -z ${HOME} ]]; then
    export HOME=/root
fi

erl -noshell -setcookie "$(cat ${cruxis_conf_dir}/cookie)" -pa ${erl_dir} \
    -name "cruxis_client_$$@127.0.0.1" -run cruxis_client cruxis_client \
    -run init stop -extra "$@"
