#!/usr/bin/env bash

if [[ $(whoami) != root ]]; then
    echo "must be run as root" 1>&2
    exit 1
fi

python_dir=/usr/lib/cruxis
bin_dir=/usr/bin
cruxis_src_dir="$(dirname "$(realpath "$0")")"
cruxis_conf_dir=/etc/cruxis
systemd_conf_dir=/etc/systemd/system
dbus_conf_dir=/etc/dbus-1/system.d

if [[ ! -d ${python_dir} ]]; then
    mkdir ${python_dir}
fi

if [[ ! -d ${cruxis_conf_dir} ]]; then
    mkdir ${cruxis_conf_dir}
fi

if [[ ! -d ${cruxis_conf_dir}/networks.d ]]; then
    mkdir ${cruxis_conf_dir}/networks.d
fi

if [[ ! -f ${cruxis_conf_dir}/networks ]]; then
    touch ${cruxis_conf_dir}/networks
fi

cp "${cruxis_src_dir}"/*.py "${python_dir}"
cp "${cruxis_src_dir}/cruxis-daemon" /usr/sbin/
cp "${cruxis_src_dir}/cruxis" /usr/bin/

cp "${cruxis_src_dir}/org.zelos.cruxis.conf" "${dbus_conf_dir}/"
cp "${cruxis_src_dir}/cruxis-daemon.service" "${systemd_conf_dir}/"

# TODO: should this be conditional?
systemctl --system daemon-reload
systemctl reload cruxis-daemon.service
