#!/usr/bin/env bash

if [[ $(whoami) != root ]]; then
    echo "must be run as root" 1>&2
    exit 1
fi

cruxis_dir=/usr/lib/cruxis
cruxis_install_dir="$(dirname "$(realpath "$0")")"
cruxis_src_dir="${cruxis_install_dir}"/../src
cruxis_conf_dir=/etc/cruxis
systemd_conf_dir=/etc/systemd/system
dbus_conf_dir=/etc/dbus-1/system.d
bin_dir=/usr/bin

systemctl stop cruxis-daemon

if [[ ! -d ${cruxis_dir} ]]; then
    mkdir "${cruxis_dir}"
fi

if [[ ! -d ${cruxis_conf_dir} ]]; then
    mkdir "${cruxis_conf_dir}"
fi

if [[ ! -d ${cruxis_conf_dir}/networks.d ]]; then
    mkdir "${cruxis_conf_dir}/networks.d"
fi

if [[ ! -f ${cruxis_conf_dir}/networks ]]; then
    touch "${cruxis_conf_dir}/networks"
fi

cp -r "${cruxis_src_dir}" "${cruxis_dir}"
cp "${cruxis_install_dir}/cruxis-daemon" "${bin_dir}"
cp "${cruxis_install_dir}/cruxis" "${bin_dir}"

cp "${cruxis_install_dir}/org.zelos.cruxis.conf" "${dbus_conf_dir}/"
cp "${cruxis_install_dir}/cruxis-daemon.service" "${systemd_conf_dir}/"

systemctl --system daemon-reload
systemctl start cruxis-daemon
